In [ ]:
import pandas as pd
import re

In [2]:
df = pd.read_csv('../data/laptop_cleaned.csv')

In [3]:
df.head()

,Model,Price (₹),Rating,Generation,Core,Ram,Storage,Display,Graphics,OS,Warranty
0,HP Victus 15-fb0157AX Gaming Laptop (AMD Ryzen...,50399,70.0,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8,512,"15.6 inches, 1920 x 1080 pixels, Touch Screen",4 GB AMD Radeon RX 6500M,Windows 11 OS,1
1,Tecno Megabook T1 Laptop (11th Gen Core i3/ 8G...,23990,56.0,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8,512,"15.6 inches, 1920 x 1080 pixels",Intel UHD Graphics,Windows 11 OS,1
2,Lenovo V15 G4 ‎82YU00W7IN Laptop (AMD Ryzen 3 ...,26989,55.0,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",8,512,"15.6 inches, 1920 x 1080 pixels",AMD Radeon Graphics,Windows 11 OS,1
3,Samsung Galaxy Book2 Pro 13 Laptop (12th Gen C...,69990,60.0,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16,512,"13.3 inches, 1080 x 1920 pixels",Intel Iris Xe Graphics,Windows 11 OS,1
4,Xiaomi Redmi G Pro 2024 Gaming Laptop (14th Ge...,102990,78.0,14th Gen Intel Core i9 14900HX,"24 Cores (8P + 16E), 32 Threads",16,1024,"16.1 inches, 2560 x 1600 pixels",8 GB NVIDIA GeForce RTX 4060,Windows 11 OS,1

## One-Hot Encoding for 'OS' column

In [4]:
df['OS'].value_counts()

OS
Windows 11 OS        845
Mac OS                18
DOS OS                15
Chrome OS              9
Windows 10 OS          6
Windows OS             4
Ubuntu OS              2
Windows 11 Pro OS      1
Backlit Keyboard       1
DOS 3.0 OS             1
Name: count, dtype: int64

In [5]:
df = pd.get_dummies(df, columns=['OS'], dtype=int)

## Handling 'Display' column

In [6]:
df['Display'].unique()

array(['15.6\u2009inches, 1920\u2009x\u20091080\u2009pixels, Touch Screen',
       '15.6\u2009inches, 1920\u2009x\u20091080\u2009pixels',
       '13.3\u2009inches, 1080\u2009x\u20091920\u2009pixels',
       '16.1\u2009inches, 2560\u2009x\u20091600\u2009pixels',
       '13.3\u2009inches, 2560\u2009x\u20091600\u2009pixels',
       '15.6\u2009inches, 1080\u2009x\u20091920\u2009pixels',
       '16.1\u2009inches, 1920\u2009x\u20091080\u2009pixels',
       '13.6\u2009inches, 2560\u2009x\u20091664\u2009pixels',
       '14\u2009inches, 1920\u2009x\u20091080\u2009pixels',
       '14\u2009inches, 1920\u2009x\u20091200\u2009pixels',
       '14\u2009inches, 1920\u2009x\u20091200\u2009pixels, Touch Screen',
       '14\u2009inches, 2880\u2009x\u20091800\u2009pixels',
       '13.4\u2009inches, 1920\u2009x\u20091200\u2009pixels, Touch Screen',
       '16\u2009inches, 2880\u2009x\u20091800\u2009pixels, Touch Screen',
       '16\u2009inches, 1920\u2009x\u20091200\u2009pixels',
       '15.6\u2009inches, 1366\u2009x\u2009768\u2009pixels',
       '16.1\u2009inches, 2560\u2009x\u20091440\u2009pixels',
       '13.3\u2009inches, 1080\u2009x\u20091920\u2009pixels, Touch Screen',
       '16\u2009inches, 2560\u2009x\u20091600\u2009pixels',
       '13.5\u2009inches, 3000\u2009x\u20092000\u2009pixels, Touch Screen',
       '16\u2009inches, 1440\u2009x\u20092560\u2009pixels',
       '15.6\u2009inches, 2560\u2009x\u20091440\u2009pixels',
       '16.2\u2009inches, 3456\u2009x\u20092234\u2009pixels',
       '14\u2009inches, 1366\u2009x\u2009768\u2009pixels',
       '11.6\u2009inches, 1366\u2009x\u2009768\u2009pixels',
       '13.3\u2009inches, 2880\u2009x\u20091800\u2009pixels',
       '17.3\u2009inches, 1920\u2009x\u20091080\u2009pixels',
       '15.3\u2009inches, 2880\u2009x\u20091864\u2009pixels',
       '16\u2009inches, 3072\u2009x\u20091920\u2009pixels',
       '16\u2009inches, 3200\u2009x\u20092000\u2009pixels',
       '14\u2009inches, 2880\u2009x\u20091800\u2009pixels, Touch Screen',
       '14\u2009inches, 1920\u2009x\u20091080\u2009pixels, Touch Screen',
       '13.3\u2009inches, 1920\u2009x\u20091080\u2009pixels, Touch Screen',
       '14.2\u2009inches, 3024\u2009x\u20091964\u2009pixels',
       '15\u2009inches, 1920\u2009x\u20091080\u2009pixels',
       '14\u2009inches, 2240\u2009x\u20091400\u2009pixels',
       '13.5\u2009inches, 2256\u2009x\u20091504\u2009pixels, Touch Screen',
       '14.1\u2009inches, 1920\u2009x\u20091080\u2009pixels',
       '17.3\u2009inches, 3840\u2009x\u20092160\u2009pixels',
       '17.3\u2009inches, 2560\u2009x\u20091440\u2009pixels',
       '15.6\u2009inches, 2880\u2009x\u20091800\u2009pixels',
       '15.75\u2009inches, 1920\u2009x\u20091080\u2009pixels',
       '17\u2009inches, 2560\u2009x\u20091600\u2009pixels',
       '15.6\u2009inches, 2880\u2009x\u20091620\u2009pixels',
       '16\u2009inches, 1920\u2009x\u20091080\u2009pixels',
       '16\u2009inches, 2561\u2009x\u20091600\u2009pixels',
       '12\u2009inches, 2160\u2009x\u20091440\u2009pixels',
       '17\u2009inches, 1920\u2009x\u20091080\u2009pixels',
       '14\u2009inches, 2160\u2009x\u20091440\u2009pixels',
       '14.1\u2009inches, 1366\u2009x\u2009768\u2009pixels',
       '13.3\u2009inches, 2048\u2009x\u20091536\u2009pixels, Touch Screen',
       '13.3\u2009inches, 1920\u2009x\u20091200\u2009pixels',
       '14.2\u2009inches, 2520\u2009x\u20091680\u2009pixels, Touch Screen',
       '13.3\u2009inches, 2560\u2009x\u20091600\u2009pixels, Touch Screen',
       '15.6\u2009inches, 1366\u2009x\u2009720\u2009pixels',
       '12.4\u2009inches, 1536\u2009x\u20091024\u2009pixels, Touch Screen',
       '14\u2009inches, 1080\u2009x\u20091920\u2009pixels',
       '11.6\u2009inches, 1280\u2009x\u20091024\u2009pixels',
       '13.3\u2009inches, 1920\u2009x\u20091200\u2009pixels, Touch Screen',
       '14.5\u2009inches, 2560\u2009x\u20091600\u2009pixels',
       '17\u2009inches, 1920\u2009x\u20092560\u2009pixels, Touch Screen',
       '13.3\u2009inches, 1920\u2009x\u20091080\u2009pixels',
       '16\u2009inches, 3840\u2009x\u20092400\u2009pixels',
       '13.5\u2009inches, 1920\u2009x\u20091280\u2009pixels, Touch Screen',
       '13.3\u2009inches, 2880\u2009x\u20091800\u2009pixels, Touch Screen',
       '15.6\u2009inches, 3456\u2009x\u20092160\u2009pixels, Touch Screen',
       '16\u2009inches, 3200\u2009x\u20091800\u2009pixels',
       '18\u2009inches, 3200\u2009x\u20091800\u2009pixels',
       '14\u2009inches, 1200\u2009x\u20091920\u2009pixels',
       '16\u2009inches',
       '16\u2009inches, 1920\u2009x\u20091200\u2009pixels, Touch Screen',
       '14\u2009inches, 2560\u2009x\u20091600\u2009pixels',
       '16\u2009inches, 1600\u2009x\u20092560\u2009pixels, Touch Screen',
       '17\u2009inches, 3840\u2009x\u20092400\u2009pixels, Touch Screen',
       '13.4\u2009inches, 3840\u2009x\u20092400\u2009pixels, Touch Screen',
       '17\u2009inches, 1600\u2009x\u20092560\u2009pixels',
       '14\u2009inches, 1200\u2009x\u20091920\u2009pixels, Touch Screen',
       '15\u2009inches, 1366\u2009x\u2009768\u2009pixels'], dtype=object)

In [7]:
df['Display'] = df['Display'].str.replace('\u2009', ' ')

In [8]:
df['Screen Size'] = df['Display'].str.extract('(^\d+\.?\d+)')

In [9]:
df['Touch Screen'] = pd.Series(1 if 'Touch Screen' in x else 0 for x in df['Display'])

In [10]:
resolution = df['Display'].str.extract('(\d+)\s*[Xx]\s*(\d+)')
df['Total_Pixels'] = resolution[0].astype(float) * resolution[1].astype(float)

In [11]:
df = df.drop(['Display'], axis=1)

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 902 entries, 0 to 901
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Model                 902 non-null    object
 1   Price (₹)             902 non-null    int64
 2   Rating                902 non-null    float64
 3   Generation            902 non-null    object
 4   Core                  902 non-null    object
 5   Ram                   902 non-null    int64
 6   Storage               902 non-null    int64
 7   Graphics              902 non-null    object
 8   Warranty              902 non-null    int64
 9   OS_Backlit Keyboard   902 non-null    int32
 10  OS_Chrome OS          902 non-null    int32
 11  OS_DOS 3.0 OS         902 non-null    int32
 12  OS_DOS OS             902 non-null    int32
 13  OS_Mac OS             902 non-null    int32
 14  OS_Ubuntu OS          902 non-null    int32
 15  OS_Windows 10 OS      902 non-null    int32
 16  OS_Windows 11 OS      902 non-null    int32
 17  OS_Windows 11 Pro OS  902 non-null    int32
 18  OS_Windows OS         902 non-null    int32
 19  Screen Size           902 non-null    object
 20  Touch Screen          902 non-null    int64
 21  Total_Pixels          901 non-null    float64
dtypes: float64(2), int32(10), int64(5), object(5)
memory usage: 119.9+ KB

In [13]:
df['Screen Size'] = df['Screen Size'].astype(float)

In [14]:
df.head()

,Model,Price (₹),Rating,Generation,Core,Ram,Storage,Graphics,Warranty,OS_Backlit Keyboard,...,OS_DOS OS,OS_Mac OS,OS_Ubuntu OS,OS_Windows 10 OS,OS_Windows 11 OS,OS_Windows 11 Pro OS,OS_Windows OS,Screen Size,Touch Screen,Total_Pixels
0,HP Victus 15-fb0157AX Gaming Laptop (AMD Ryzen...,50399,70.0,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8,512,4 GB AMD Radeon RX 6500M,1,0,...,0,0,0,0,1,0,0,15.6,1,2073600.0
1,Tecno Megabook T1 Laptop (11th Gen Core i3/ 8G...,23990,56.0,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8,512,Intel UHD Graphics,1,0,...,0,0,0,0,1,0,0,15.6,0,2073600.0
2,Lenovo V15 G4 ‎82YU00W7IN Laptop (AMD Ryzen 3 ...,26989,55.0,7th Gen AMD Ryzen 3 7320U,"Quad Core, 8 Threads",8,512,AMD Radeon Graphics,1,0,...,0,0,0,0,1,0,0,15.6,0,2073600.0
3,Samsung Galaxy Book2 Pro 13 Laptop (12th Gen C...,69990,60.0,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16,512,Intel Iris Xe Graphics,1,0,...,0,0,0,0,1,0,0,13.3,0,2073600.0
4,Xiaomi Redmi G Pro 2024 Gaming Laptop (14th Ge...,102990,78.0,14th Gen Intel Core i9 14900HX,"24 Cores (8P + 16E), 32 Threads",16,1024,8 GB NVIDIA GeForce RTX 4060,1,0,...,0,0,0,0,1,0,0,16.1,0,4096000.0

In [15]:
df = df.dropna()

## Handling 'Graphics' column

In [16]:
df['Graphics'].unique()

array(['4\u2009GB AMD Radeon RX 6500M', 'Intel UHD Graphics',
       'AMD Radeon Graphics', 'Intel Iris Xe Graphics',
       '8\u2009GB NVIDIA GeForce RTX 4060',
       'Apple M1 Integrated Graphics', 'Intel Integrated UHD',
       'Intel Integrated Iris Xe', '4\u2009GB NVIDIA GeForce RTX 2050',
       'Intel Graphics', 'Intel Integrated', 'Intel Iris Xe',
       '6\u2009GB NVIDIA GeForce RTX 3050', 'Apple 8 Core GPU',
       '8-Core GPU', '4\u2009GB NVIDIA GeForce GTX 1650',
       'AMD Raedon Graphics', '4\u2009GB NVIDIA GeForce RTX 3050',
       'Intel Iris Xe Graphics comes', 'Integrated Intel Graphics',
       'Integrated AMD Radeon Graphics',
       '4\u2009GB \u200eNVIDIA GeForce RTX 3050', 'Intel Arc Graphics',
       'AMD Radeon AMD', '4\u2009GB NVIDIA GeForce RTX 3050 Ti',
       '6\u2009GB NVIDIA GeForce RTX 4050',
       '6\u2009GB NVIDIA Geforce RTX 4050', 'AMD Integrated',
       '8\u2009GB NVIDIA GeForce RTX 3070 Ti ',
       'AMD Radeon Vega 8 Graphics', '16\u2009GB NVIDIA GeForce RTX 4090',
       'Intel Integrated UHD Graphics', '40 Core GPU',
       '\u200eIntel UHD Graphics', '4\u2009GB NVIDIA GeForce RTX 3050 ',
       'Integrated Intel UHD Graphics', 'AMD Radeon Radeon Graphics',
       '4\u2009GB NVIDIA GeForce GTX 3050', 'AMD Radeon Vega 7',
       'Intel HD Graphics', 'NVIDIA GeForce RTX 3050',
       '12\u2009GB NVIDIA Geforce RTX 4080',
       'Intel Integrated Intel Iris Xe Graphics',
       '4\u2009GB NVIDIA RTX A500', '10-Core GPU', 'Apple 10 Core GPU',
       '8\u2009GB NVIDIA GeForce RTX 4070', 'Intel  ARC Graphics',
       'Intel Integrated Integrated', 'Intel ARC Graphics', '30 Core GPU',
       '14 Core GPU', 'AMD Radeon 610M', '10 Core GPU',
       '4\u2009GB AMD Radeon RX6550M',
       'Integrated Intel Iris Xe Graphics', 'Intel Integrated Graphics',
       'Intel Integrated Intel UHD Graphics',
       '4\u2009GB AMD Radeon RX 6500M Graphics', 'AMD Graphics',
       'Intel Iris Xe Graphics ', '4\u2009GB NVIDIA Geforce RTX 3050',
       '12\u2009GB Nvidia GeForce RTX4080',
       '16\u2009GB NVIDIA GeForce RTX 3080Ti',
       '6\u2009GB NVIDIA GeForce RTX 3060', 'Intel UHD Graphics 600',
       'AMD Radeon Integrated Graphics',
       '12\u2009GB NVIDIA GeForce RTX 4080', 'Intel Integrated Arc',
       'AMD Radeon Radeon', 'Intel Integrated Intel Iris Xe',
       'Intel Integrated ARC Graphics', 'Arm Mali G52 MC2 2EE Graphics',
       'Arm Mali G52 MC2 2EE', '4\u2009GB Intel Integrated ARC A530M',
       'Intel Integrated Intel UHD', 'AMD Radeon',
       'Integrated Intel IrisXe Graphics', 'Intel UHD Graphics ',
       '12\u2009GB NVIDIA GeForce RTX 3500 Ada', '18 Core GPU',
       'Intel Iris Xe Graphic', '4\u2009GB NVIDIA GeForce GTX 1650 Max Q',
       '4\u2009GB NVIDIA GeForce RTX 2050 ',
       '16\u2009GB NVIDIA GeForce RTX 4090 ', 'AMD Radeon 780M Graphics',
       '8\u2009GB NVIDIA RTX 3000 Ada',
       '4\u2009GB NVIDIA GeForce RTX RTX 3050',
       '4\u2009GB  NVIDIA GeForce RTX 2050', 'AMD Radeon 610M Graphics',
       'Intel Integrated Graphics ',
       '8\u2009GB NVIDIA GeForce RTX A2000 Ada',
       '4\u2009GB NVIDIA GeForce GTX 2050', 'Intel Integrated Iris',
       'Intel Integrated UHD 600', '\u200eIntel Iris Xe Graphics',
       'Intel Integrated Integrated Intel® UHD Graphics',
       'NVIDIA Geforce RTX', 'Integrated Intel UHD Graphics 600',
       'AMD Integrated SoC', '4\u2009GB NVIDIA GeForce RTX 3050 GPU',
       '4\u2009GB AMD Radeon AMD Radeon RX 6500M',
       '6\u2009GB NVIDIA RTX 4050', 'Intel Iris Xe Integrated Graphics',
       '2\u2009GB NVIDIA GeForce MX450',
       '8\u2009GB NVIDIA GEFORCE RTX 4060',
       '4\u2009GB NVIDIA GeForce RTX2050',
       '12\u2009GB NVIDIA GEFORCE RTX 4080', 'Intel Iris Xᵉ Graphics',
       '4\u2009GB NVIDIA RTX NVIDIA T550',
       '12\u2009GB NVIDIA GeForce RTX 3080 Ti', 'AMD Radeon 7 Graphics',
       '8\u2009GB NVIDIA Geforce RTX 4060',
       '6\u2009GB NVIDIA GeForce RTX 3050 ', '4\u2009GB NVIDIA GTX 1650',
       'Iris Xe Graphics', 'Intel Iris X Graphics',
       '4\u2009GB \u200eNVIDIA Quadro T600', 'AMD Radeon 680M',
       'Intel UHD', '4\u2009GB NVIDIA Geforce RTX 2050',
       '8\u2009GB Nvidia GeForce RTX 4060',
       '6\u2009GB Nvidia GeForce RTX 4050',
       '2\u2009GB NVIDIA GeForce MX570', '4\u2009GB Nvidia RTX 3050',
       '4\u2009GB NVIDIA GeForce GTX 1650 ',
       '6\u2009GB NVIDIA GEFORCE RTX 4050', 'Intel UHD Integrated',
       '4\u2009GB AMD Radeon RX 5600M ',
       '8\u2009GB NVIDIA GeForce RTX 4060 ',
       '4\u2009GB AMD Radeon RX6500M'], dtype=object)

In [17]:
df['Graphics'] = df['Graphics'].str.replace('\u2009', ' ')
df['Graphics'] = df['Graphics'].str.replace('\u200e', '')

In [18]:
df['VRAM'] = df['Graphics'].str.extract('(^\d+)')
df['VRAM'] = df['VRAM'].fillna(0)
df['VRAM'] = df['VRAM'].astype(int)

In [19]:
def get_gpu_brand(text):
    text = text.lower()
    if 'amd' in text: return 'AMD'
    if 'intel' in text: return 'Intel'
    if 'nvidia' in text: return 'NVIDIA'
    if 'apple' in text or 'mac' in text or 'core gpu' in text: return 'Apple'
    return 'Other'

df['GPU brand'] = df['Graphics'].apply(get_gpu_brand)

In [20]:
df = df.drop('Graphics', axis=1)

In [21]:
df = pd.get_dummies(data=df, columns=['GPU brand'], dtype=int)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 901 entries, 0 to 901
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Model                 901 non-null    object
 1   Price (₹)             901 non-null    int64
 2   Rating                901 non-null    float64
 3   Generation            901 non-null    object
 4   Core                  901 non-null    object
 5   Ram                   901 non-null    int64
 6   Storage               901 non-null    int64
 7   Warranty              901 non-null    int64
 8   OS_Backlit Keyboard   901 non-null    int32
 9   OS_Chrome OS          901 non-null    int32
 10  OS_DOS 3.0 OS         901 non-null    int32
 11  OS_DOS OS             901 non-null    int32
 12  OS_Mac OS             901 non-null    int32
 13  OS_Ubuntu OS          901 non-null    int32
 14  OS_Windows 10 OS      901 non-null    int32
 15  OS_Windows 11 OS      901 non-null    int32
 16  OS_Windows 11 Pro OS  901 non-null    int32
 17  OS_Windows OS         901 non-null    int32
 18  Screen Size           901 non-null    float64
 19  Touch Screen          901 non-null    int64
 20  Total_Pixels          901 non-null    float64
 21  VRAM                  901 non-null    int32
 22  GPU brand_AMD         901 non-null    int32
 23  GPU brand_Apple       901 non-null    int32
 24  GPU brand_Intel       901 non-null    int32
 25  GPU brand_NVIDIA      901 non-null    int32
 26  GPU brand_Other       901 non-null    int32
dtypes: float64(3), int32(16), int64(5), object(3)
memory usage: 140.8+ KB

## Handling 'Core' column

In [22]:
df['Core'].unique()

array(['Hexa Core, 12 Threads', 'Dual Core, 4 Threads',
       'Quad Core, 8 Threads', '12 Cores (4P + 8E), 16 Threads',
       '24 Cores (8P + 16E), 32 Threads',
       'Hexa Core (2P + 4E), 8 Threads', 'Octa Core (4P + 4E)',
       '10 Cores (2P + 8E), 12 Threads', 'Octa Core, 16 Threads',
       '12 Cores (2P + 8E + 2LP-E), 14 Threads',
       '16 Cores (6P + 8E + 2LP-E), 22 Threads',
       'Octa Core (4P + 4E), 12 Threads',
       '10 Cores (6P + 4E), 16 Threads', 'Dual Core, 2 Threads',
       '14 Cores (6P + 8E), 20 Threads',
       '14 Cores (4P + 8E + 2LP-E), 18 Threads',
       '20 Cores (8P + 12E), 28 Threads', '16 Cores (12P + 4E)',
       '14 Cores (6P + 8E)', 'Quad Core, 4 Threads',
       '16 Cores (8P + 8E), 24 Threads', 'Quad Core',
       '14 Cores (10P + 4E)', '11 Cores (5P + 6E)',
       '14 Cores, 20 Threads', '5 Cores (1P + 4E), 6 Threads',
       'Octa Core', '5 Cores, 5 Threads', 'Octa Core, 8 Threads',
       '12 Cores (6P + 6E)', 'Dual Core', '24 Cores (8P + 16E)',
       '20 Threads', '12 Cores, 24 Threads'], dtype=object)

In [23]:
df['Thread'] = df['Core'].str.split(',', expand=True)[1]
df['Core'] = df['Core'].str.split(',', expand=True)[0]

In [24]:
df['Thread'] = df['Thread'].str.extract('(\d+)')
df['Thread'] = df['Thread'].astype(float)

In [25]:
df['Core'].value_counts()

Core
10 Cores (2P + 8E)            135
Hexa Core                     104
Octa Core                      98
Quad Core                      95
Octa Core (4P + 4E)            77
Dual Core                      70
12 Cores (4P + 8E)             65
14 Cores (6P + 8E)             59
Hexa Core (2P + 4E)            59
10 Cores (6P + 4E)             38
16 Cores (6P + 8E + 2LP-E)     26
24 Cores (8P + 16E)            23
16 Cores (8P + 8E)             13
14 Cores (4P + 8E + 2LP-E)     11
5 Cores (1P + 4E)               9
12 Cores (2P + 8E + 2LP-E)      5
20 Cores (8P + 12E)             3
12 Cores (6P + 6E)              3
14 Cores (10P + 4E)             2
16 Cores (12P + 4E)             1
11 Cores (5P + 6E)              1
14 Cores                        1
5 Cores                         1
20 Threads                      1
12 Cores                        1
Name: count, dtype: int64

In [26]:
def get_cpu_brand(text):
    if 'intel' in text or 'celeron' in text or 'pentium' in text: return 'Intel'
    if 'amd' in text or 'ryzen' in text or 'athlon' in text: return 'AMD'
    if 'apple' in text or 'm1' in text or 'm2' in text or 'm3' in text: return 'Apple'
    return 'Other'

df['CPU_Brand'] = df['Generation'].apply(get_cpu_brand)

In [27]:
def transform_core_data(text):
    val = re.search('(\d+)', str(text))
    if not val:
        text = text.lower()
        if 'dual' in text: return 2
        if 'quad' in text: return 4
        if 'hexa' in text: return 6
        if 'octa' in text: return 8
    return val.group(0)

df['Core'] = df['Core'].apply(transform_core_data)

In [28]:
df['Core'] = df['Core'].astype(int)

In [29]:
df['Thread'] = df['Thread'].fillna(df.groupby('Core')['Thread'].transform('median'))
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 901 entries, 0 to 901
Data columns (total 29 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Model                 901 non-null    object
 1   Price (₹)             901 non-null    int64
 2   Rating                901 non-null    float64
 3   Generation            901 non-null    object
 4   Core                  901 non-null    int32
 5   Ram                   901 non-null    int64
 6   Storage               901 non-null    int64
 7   Warranty              901 non-null    int64
 8   OS_Backlit Keyboard   901 non-null    int32
 9   OS_Chrome OS          901 non-null    int32
 10  OS_DOS 3.0 OS         901 non-null    int32
 11  OS_DOS OS             901 non-null    int32
 12  OS_Mac OS             901 non-null    int32
 13  OS_Ubuntu OS          901 non-null    int32
 14  OS_Windows 10 OS      901 non-null    int32
 15  OS_Windows 11 OS      901 non-null    int32
 16  OS_Windows 11 Pro OS  901 non-null    int32
 17  OS_Windows OS         901 non-null    int32
 18  Screen Size           901 non-null    float64
 19  Touch Screen          901 non-null    int64
 20  Total_Pixels          901 non-null    float64
 21  VRAM                  901 non-null    int32
 22  GPU brand_AMD         901 non-null    int32
 23  GPU brand_Apple       901 non-null    int32
 24  GPU brand_Intel       901 non-null    int32
 25  GPU brand_NVIDIA      901 non-null    int32
 26  GPU brand_Other       901 non-null    int32
 27  Thread                900 non-null    float64
 28  CPU_Brand             901 non-null    object
dtypes: float64(4), int32(17), int64(5), object(3)
memory usage: 151.3+ KB

In [30]:
df[df['Thread'].isnull()]

,Model,Price (₹),Rating,Generation,Core,Ram,Storage,Warranty,OS_Backlit Keyboard,OS_Chrome OS,...,Touch Screen,Total_Pixels,VRAM,GPU brand_AMD,GPU brand_Apple,GPU brand_Intel,GPU brand_NVIDIA,GPU brand_Other,Thread,CPU_Brand
156,Apple MacBook Pro 14 2023 Laptop (Apple M3 Pro...,186899,54.0,Apple M3 Pro,11,18,512,1,0,0,...,0,5939136.0,14,0,1,0,0,0,NaN,Other

In [31]:
df.groupby('Core')['Thread'].median()

Core
2      4.0
4      8.0
5      6.0
6     12.0
8     16.0
10    12.0
11     NaN
12    16.0
14    20.0
16    22.0
20    28.0
24    32.0
Name: Thread, dtype: float64

In [32]:
df['Thread'] = df['Thread'].fillna(14.0)

## Handling 'Generation' column

In [33]:
df['Generation'].unique()

array(['5th Gen AMD Ryzen 5 5600H', '11th Gen Intel Core i3 1115G4',
       '7th Gen AMD Ryzen 3 7320U', '12th Gen Intel Core i5 1240P',
       '14th Gen Intel Core i9 14900HX', '12th Gen Intel Core i3 1215U',
       'Apple M1', '12th Gen Intel Core i5 1235U',
       '7th Gen Amd Ryzen 5 7535HS', '11th Gen Intel Core i5 1135G7',
       '12th Gen Intel Core i5 12500H', '7th Gen AMD Ryzen 7 7840HS',
       'Apple M3', '5th Gen AMD Ryzen 3 5300U', 'Apple M2',
       'Intel Core 5 Processor Series 1 120U',
       '11th Gen Intel Core i5 11400H ', '5th Gen AMD Ryzen 7 5800U',
       '13th Gen Intel Core i7 1355U', 'Intel Core 3 Processor 100U',
       'Intel Core Ultra 7 155U', 'Intel Core Ultra 7 Series 1 155H',
       'Intel Core Ultra 5 125U', '12th Gen Intel Core i5 12450H',
       'Intel Core 7 Processor Series 1 150U',
       '13th Gen Intel Core i5 13450HX',
       '6th Gen AMD Ryzen 9 6900HS\u200b', '7th Gen AMD Ryzen 3 7330U',
       '11th Gen Intel Core i7 11800H', '13th Gen Intel Core i5 13420H',
       '12th Gen Intel Core i7 12650H', '3rd Gen AMD Athlon 3050U',
       '12th Gen Intel Core i7 12700H', '6th Gen AMD Ryzen 7  6800H',
       '7th Gen AMD Ryzen 7 7730U', 'Intel Core Ultra 5 Series 1 125H',
       '8th Gen AMD Ryzen 7 8840HS', '14th Gen Intel Core i7 14700HX',
       'Intel Core Ultra 7 155H', 'Apple M3 Max',
       '12th Gen Intel Core i3 1220P', '13th Gen Intel Core i7 1360P',
       '13th Gen Intel Core i7 13650HX', '11th Gen Intel Core i5 1155G7',
       '12th Gen Intel Core i7 1255U', '11th Gen Intel Core i5 11260H',
       'intel Celeron  N4020', '11th Gen Intel Celeron N5100',
       '7th Gen AMD Ryzen 5 7535HS', '5th Gen AMD Ryzen 5 5500U',
       '13th Gen Intel Core i9 13900H', '7th Gen AMD Ryzen 7 7735HS',
       '13th Gen Intel Core i7 13700HX', '3rd Gen AMD Ryzen 3 3250U',
       '7th Gen AMD Ryzen 5 7530U', '12th Gen Intel Core i5 1235U ',
       '5th Gen AMD Ryzen 7  5800H', '5th Gen AMD Ryzen 5 5600H ',
       'Intel Atom Quad Core Z3735F', '8th Gen AMD Ryzen 7 8845HS',
       '11th Gen Intel Core i7 1165G7', 'Intel Pentium Gold 7505',
       '13th Gen Intel Core i5 1334U', '13th Gen Intel Core i5 1335U',
       '13th Gen Intel Core i3 1315U', '7th Gen AMD Ryzen 5 7520U',
       'Intel Core i9 14900HX', '6th Gen AMD Ryzen 7 6800H',
       '13th Gen Intel Core i5 13500H', 'Apple M3 Pro',
       'AMD Athlon Silver 7120U', '7th Gen AMD Ryzen 5 7520U ',
       '11th Gen Intel Core i3 1125G4', '12th Gen Intel Core i7 12700H ',
       '11th Gen intel Core i3 1115G4', '12th Gen Intel Core i5 12500H ',
       'Intel Celeron  N4020', '13th Gen Intel Core i5 1340P',
       '11th Gen Intel Core i3  1115G4', '5th Gen AMD Ryzen 7 5800H',
       '5th Gen AMD Ryzen 5  5600H ', '12th Gen Intel Core i9 12900HX',
       '6th Gen AMD Ryzen 7 6800H ', '4th Gen Intel Celeron N4020',
       '7th Gen AMD Ryzen 7 7840U', '8th Gen AMD Ryzen 5 8640HS',
       '13th Gen Intel Core i7 13700H',
       'Intel Core Ultra 9 Series 1 185H', 'Intel \u200eCeleron N4020',
       '12th Gen Intel Celeron N100', '13th Gen Intel Core i7 13620H',
       '11th Gen Intel Core i5 11400H', '5th Gen AMD Ryzen 7 5700U',
       '13th Gen Intel Core i3 1305U', '10th Gen Intel Core i5 10210Y',
       'Intel Pentium N100', 'MediaTek Kompanio 520 Kompanio 520',
       'MediaTek Kompanio Kompanio 520', '12th Gen intel Core i5 12450HX',
       '12th Gen Intel N100 N100', '10th Gen Intel Core i5 1035G1',
       'Intel Celeron N4020', '11th Gen Intel Core i5 L16G7',
       '13th Gen Intel Core i9 13900HX', '12th Gen intel Core i5 12450H',
       '11th Gen Intel Core i5 1135G7 ', '5th Gen AMD Ryzen 5  5500U',
       '8th Gen Amd Ryzen 7 8845HS', '5th Gen AMD Ryzen 7  5700U',
       '13th Gen Intel Core i9 13980HX', 'Intel Core i3 N305',
       '12th Gen Intel Core i7 1260P', '5th Gen AMD Ryzen 5 5500H',
       '11th Gen Intel Core i5 11320H', '5th Gen AMD Ryzen 7 5800HS',
       '7th Gen AMD Ryzen 7  7730U', 'Intel Celeron  N4500',
       '12th Gen Intel Core i5 12450H ', 'Intel Celeron N4500',
       'Intel   N4500', '7th Gen Amd Ryzen 7 7840H',
       '7th Gen AMD Ryzen 7 7745HX', '13th Gen Intel Core i9 13950HX',
       '6th Gen AMD Ryzen 7 6800HS ', '6th Gen AMD Ryzen 5 6600H',
       'Intel Celeron Dual Core N4500', '5th Gen AMD Ryzen 5  5600H',
       '4th Gen AMD Ryzen 7 PRO 4750U', '5th Gen AMD Ryzen 5  5500H',
       'AMD Athlon 7120U', '10th Gen Intel Core i3 1005G1',
       '13th Gen Intel Core i7 1355U ', '12th Gen Intel Core i7 1250U',
       '7th Gen AMD Ryzen 7 7735U', '5th Gen AMD Ryzen 5 5600HS',
       '3rd Gen AMD Ryzen 3  3250U', '10th Gen Intel Core i5 1035G4',
       '7th Gen Amd Ryzen 5 7520U', '13th Gen Intel Core i7 1365U',
       '10th Gen Intel Core i5 10210U', '11th Gen Intel Core i7 1195G7',
       '5th Gen AMD Ryzen 7 5825U', '13th Gen Intel Core i9 13900HK',
       '7th Gen Amd Ryzen 7 7745HX', '7th Gen Amd Ryzen 9 7845HX',
       '12th Gen Intel Core i7 12650H ', '12th Gen Intel Core i9 12900H',
       'Intel Pentium Silver   N6000 ', 'Intel Celeron  N4020 ',
       '6th Gen AMD Ryzen 7  7735HS', '11th Gen Intel Core i7 1165G7 ',
       '13th Gen \u200eIntel Core i5 1335U',
       '5th Gen AMD Ryzen 7   5700U', '7th Gen AMD Ryzen 9 7940HS',
       '10th Gen Intel Core i7 10750H ', '7th Gen Amd Ryzen 5 7530U',
       '7th Gen Amd Ryzen 9 7940HS', '7th Gen AMD Ryzen 7  7735HS',
       '13th Gen Intel Core i5 1340p', '13th Gen Intel Core i5 13500H ',
       '5th Gen AMD Ryzen 5  5500u', '12th Gen Intel Core i3 1215U ',
       '13th Gen Intel Core i7 13700HX ', 'Intel Pentium Silver N6000',
       '7th Gen AMD Ryzen 7040 Series 040',
       '13th Gen Intel Core i9 13900HX ',
       '13th Gen \u200eIntel Core i3 1315U'], dtype=object)

In [34]:
df['Generation'] = df['Generation'].str.replace('\u200e', '')
df['Generation'] = df['Generation'].str.replace('\u200b', '')
df['Generation'] = df['Generation'].str.lower()

In [35]:
def get_cpu_brand(text):
    if 'intel' in text or 'celeron' in text or 'pentium' in text: return 'Intel'
    if 'amd' in text or 'ryzen' in text or 'athlon' in text: return 'AMD'
    if 'apple' in text or 'm1' in text or 'm2' in text or 'm3' in text: return 'Apple'
    return 'Other'

df['CPU_Brand'] = df['Generation'].apply(get_cpu_brand)

In [36]:
def get_cpu_tier(text):
    if 'i9' in text or 'ryzen 9' in text or 'ultra 9' in text: return 'Tier 9'
    if 'i7' in text or 'ryzen 7' in text or 'core 7' in text or 'ultra 7' in text: return 'Tier 7'
    if 'i5' in text or 'ryzen 5' in text or 'core 5' in text or 'ultra 5' in text: return 'Tier 5'
    if 'i3' in text or 'ryzen 3' in text or 'core 3' in text or 'ultra 3' in text: return 'Tier 3'
    if 'm1' in text or 'm2' in text or 'm3' in text: return 'Apple Silicon'
    return 'Basic/Other' 

df['Generation'] = df['Generation'].apply(get_cpu_tier)

In [37]:
df = pd.get_dummies(df, columns=['Generation'], dtype=int)
df = pd.get_dummies(df, columns=['CPU_Brand'], dtype=int)

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 901 entries, 0 to 901
Data columns (total 37 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Model                     901 non-null    object
 1   Price (₹)                 901 non-null    int64
 2   Rating                    901 non-null    float64
 3   Core                      901 non-null    int32
 4   Ram                       901 non-null    int64
 5   Storage                   901 non-null    int64
 6   Warranty                  901 non-null    int64
 7   OS_Backlit Keyboard       901 non-null    int32
 8   OS_Chrome OS              901 non-null    int32
 9   OS_DOS 3.0 OS             901 non-null    int32
 10  OS_DOS OS                 901 non-null    int32
 11  OS_Mac OS                 901 non-null    int32
 12  OS_Ubuntu OS              901 non-null    int32
 13  OS_Windows 10 OS          901 non-null    int32
 14  OS_Windows 11 OS          901 non-null    int32
 15  OS_Windows 11 Pro OS      901 non-null    int32
 16  OS_Windows OS             901 non-null    int32
 17  Screen Size               901 non-null    float64
 18  Touch Screen              901 non-null    int64
 19  Total_Pixels              901 non-null    float64
 20  VRAM                      901 non-null    int32
 21  GPU brand_AMD             901 non-null    int32
 22  GPU brand_Apple           901 non-null    int32
 23  GPU brand_Intel           901 non-null    int32
 24  GPU brand_NVIDIA          901 non-null    int32
 25  GPU brand_Other           901 non-null    int32
 26  Thread                    901 non-null    float64
 27  Generation_Apple Silicon  901 non-null    int32
 28  Generation_Basic/Other    901 non-null    int32
 29  Generation_Tier 3         901 non-null    int32
 30  Generation_Tier 5         901 non-null    int32
 31  Generation_Tier 7         901 non-null    int32
 32  Generation_Tier 9         901 non-null    int32
 33  CPU_Brand_AMD             901 non-null    int32
 34  CPU_Brand_Apple           901 non-null    int32
 35  CPU_Brand_Intel           901 non-null    int32
 36  CPU_Brand_Other           901 non-null    int32
dtypes: float64(4), int32(27), int64(5), object(1)
memory usage: 172.5+ KB

In [39]:
df.set_index('Model', inplace=True)

In [40]:
df.to_csv('..\data\laptop_featured.csv', index=True)