In [ ]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/laptop_featured.csv', index_col='Model')

In [8]:
df.head(1)

,Price (₹),Rating,Core,Ram,Storage,Warranty,OS_Backlit Keyboard,OS_Chrome OS,OS_DOS 3.0 OS,OS_DOS OS,...,Generation_Apple Silicon,Generation_Basic/Other,Generation_Tier 3,Generation_Tier 5,Generation_Tier 7,Generation_Tier 9,CPU_Brand_AMD,CPU_Brand_Apple,CPU_Brand_Intel,CPU_Brand_Other
Model,,,,,,,,,,,,,,,,,,,,,
HP Victus 15-fb0157AX Gaming Laptop (AMD Ryzen 5 5600H/ 8GB/ 512GB SSD/ Win11/ 4GB Graph),50399,70.0,6,8,512,1,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0

In [4]:
from sklearn.preprocessing import MinMaxScaler

In [5]:
scaler = MinMaxScaler()

df_scaled = pd.DataFrame(scaler.fit_transform(df), columns=df.columns, index=df.index)
df_scaled.head(1)

,Price (₹),Rating,Core,Ram,Storage,Warranty,OS_Backlit Keyboard,OS_Chrome OS,OS_DOS 3.0 OS,OS_DOS OS,...,Generation_Apple Silicon,Generation_Basic/Other,Generation_Tier 3,Generation_Tier 5,Generation_Tier 7,Generation_Tier 9,CPU_Brand_AMD,CPU_Brand_Apple,CPU_Brand_Intel,CPU_Brand_Other
Model,,,,,,,,,,,,,,,,,,,,,
HP Victus 15-fb0157AX Gaming Laptop (AMD Ryzen 5 5600H/ 8GB/ 512GB SSD/ Win11/ 4GB Graph),0.082812,0.689655,0.181818,0.096774,0.11811,0.333333,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0

In [7]:
df_scaled.to_csv('..\data\laptop_scaled.csv', index=True)