In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.metrics.pairwise import cosine_similarity

In [23]:
scaled_df = pd.read_csv('..\data\laptop_scaled.csv', index_col='Model')
original_df = pd.read_csv('..\data\laptop_cleaned.csv', index_col='Model')

In [ ]:
scaled_df.head(1)

,Price (₹),Rating,Core,Ram,Storage,Warranty,OS_Backlit Keyboard,OS_Chrome OS,OS_DOS 3.0 OS,OS_DOS OS,...,Generation_Apple Silicon,Generation_Basic/Other,Generation_Tier 3,Generation_Tier 5,Generation_Tier 7,Generation_Tier 9,CPU_Brand_AMD,CPU_Brand_Apple,CPU_Brand_Intel,CPU_Brand_Other
Model,,,,,,,,,,,,,,,,,,,,,
HP Victus 15-fb0157AX Gaming Laptop (AMD Ryzen 5 5600H/ 8GB/ 512GB SSD/ Win11/ 4GB Graph),0.082812,0.689655,0.181818,0.096774,0.11811,0.333333,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0

In [ ]:
similarity_matrix = cosine_similarity(scaled_df)
similarity_df = pd.DataFrame(similarity_matrix, columns=scaled_df.index, index=scaled_df.index)
similarity_df.head(2)

Model,HP Victus 15-fb0157AX Gaming Laptop (AMD Ryzen 5 5600H/ 8GB/ 512GB SSD/ Win11/ 4GB Graph),Tecno Megabook T1 Laptop (11th Gen Core i3/ 8GB/ 512GB SSD/ Win11 Home),Lenovo V15 G4 ‎82YU00W7IN Laptop (AMD Ryzen 3 7320U/ 8GB/ 512GB SSD/ Win11 Home),Samsung Galaxy Book2 Pro 13 Laptop (12th Gen Core i5/ 16GB/ 512GB SSD/ Win11),Xiaomi Redmi G Pro 2024 Gaming Laptop (14th Gen Core i9/ 16GB/ 1TB SSD/ Win11 Home/ RTX 4060),HP 15s-fq5007TU Laptop (12th Gen Core i3/ 8GB/ 512GB SSD/ Win11 Home),Apple MacBook Air 2020 MGND3HN Laptop (Apple M1/ 8GB/ 256GB SSD/ MacOS),Samsung Galaxy Book2 NP550XED-KA1IN 15 Laptop (12th Gen Core i5/ 8GB/ 512GB SSD/ Win11),HP 15s-fq5330TU Laptop (12th Gen Core i5/ 16GB/ 512GB SSD/ Win11 Home),HP Victus 15-fb1017AX Gaming Laptop (AMD Ryzen 5 7535HS/ 16GB/ 512GB SSD/ Win11/ 4GB Graph),...,Acer Aspire Vero AV14-52P NX.KJSSI.002 Laptop (13th Gen Core i5/ 16GB/ 512GB SSD/ Win11 Home),Acer Aspire Vero AV14-52P NX.KJTSI.002 Laptop (13th Gen Core i3/ 16GB/ 512GB SSD/ Win11 Home),Acer Aspire 5 A515-58M NX.KHFSI.001 Gaming Laptop (13th Gen Core i5/ 8GB/ 512GB SSD/ Win11 Home),Asus TUF Gaming F15 2023 FX507VU-LP083WS Gaming Laptop (13th Gen Core i7/ 16GB/ 512GB SSD/ Win11 Home/ 6GB Graph),Asus TUF Gaming A15 2023 FA577XU-LP041WS Gaming Laptop (AMD Ryzen 9 7940HS/ 16GB/ 1TB SSD/ Win11 Home/ 6GB Graph),Asus Vivobook 16X 2023 K3605ZF-MB541WS Laptop (12th Gen Core i5/ 16GB/ 512GB SSD/ Win11 Home/ 4GB Graph),Asus TUF Gaming A15 2023 FA577XV-HQ036WS Gaming Laptop (AMD Ryzen 9 7940HS/ 16GB/ 1TB SSD/ Win11 Home/ 8GB Graph),Acer Aspire 5 A514-56GM Gaming Laptop (13th Gen Core i7/ 8GB/ 512GB SSD/ Win11 Home/ 4GB Graph),Lenovo IdeaPad Slim 5 82FG01B3IN Laptop (11th Gen Core i5/ 16GB/ 512GB SSD/ Win11 Home),MSI Bravo 15 B5ED-034IN Gaming Laptop (AMD Ryzen 7 5800H/ 8GB/ 512GB SSD/ Win11 Home/ 4GB Graph)
Model,,,,,,,,,,,,,,,,,,,,,
HP Victus 15-fb0157AX Gaming Laptop (AMD Ryzen 5 5600H/ 8GB/ 512GB SSD/ Win11/ 4GB Graph),1.000000,0.321073,0.701280,0.51597,0.411338,0.324453,0.106366,0.517390,0.525000,0.737114,...,0.502222,0.150802,0.521334,0.392738,0.571240,0.559638,0.551768,0.345636,0.540241,0.734390
Tecno Megabook T1 Laptop (11th Gen Core i3/ 8GB/ 512GB SSD/ Win11 Home),0.321073,1.000000,0.562863,0.73043,0.486514,0.997884,0.087866,0.765168,0.765533,0.351966,...,0.750787,0.763647,0.765679,0.533468,0.347817,0.563164,0.349681,0.535951,0.777156,0.347457

## Function that displays top N laptops similar to given one

In [10]:
def recomedate_similar_laptops(laptop_name, similarity_df, top_n=5): 
    if laptop_name not in similarity_df.index:
        return "Laptop name is not in given data base"
    
    most_similar = similarity_df[laptop_name].sort_values(ascending=False)[1:top_n+1]
    return pd.DataFrame(most_similar).transpose()